# Generated by Django 4.2.4 on 2023-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_shares', models.FloatField()),
                ('win_shares_per_48_minutes', models.FloatField()),
                ('box_plus_minus', models.FloatField()),
                ('value_over_replacement_player', models.FloatField()),
            ],
        ),
    ]
