# Generated by Django 4.0.4 on 2023-09-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_advancestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancestats',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancestats',
            name='minutes_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancestats',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='advancestats',
            name='three_point_attempt_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='advancestats',
            name='total_rebound_percentage',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='advancestats',
            name='box_plus_minus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='advancestats',
            name='value_over_replacement_player',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='advancestats',
            name='win_shares',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='advancestats',
            name='win_shares_per_48_minutes',
            field=models.FloatField(default=0.0),
        ),
    ]
