# Generated by Django 4.2.4 on 2023-10-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_advancestats_player_efficiency_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancestats',
            name='team',
            field=models.CharField(default='', max_length=200),
        ),
    ]
