# Generated by Django 4.2.4 on 2023-10-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_advancestats_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
